name: UglyTroll
author: SkyZoneMC
version: 1.0
api: 4.0.0
main: SkyZoneMC\UglyTroll\Main
description: Troll plugin for PocketMine-MP
commands:
  troll:
    description: UglyTroll main command
    aliases: [uglytroll, ug]
    usage: /troll rotate | freeze | randomtp | burn | serverlag | playerlag | fakeban | crash
    permission: uglytroll.command
permissions:
  uglytroll.command:
    description: This permission allows you to use all troll features
    default: op
  uglytroll.except:
    description: Excepts you from trolling
    default: op
  uglytroll.command.rotate:
    description: Allows to use Rotate feature
    default: op
  uglytroll.command.freeze:
    description: Allows to use Freeze feature
    default: op
  uglytroll.command.randomtp:
    description: Allows to use RandomTP feature
    default: op
  uglytroll.command.burn:
    description: Allows to use Burn feature
    default: op
  uglytroll.command.serverlag:
    description: Allows to use ServerLag feature
    default: op
  uglytroll.command.playerlag:
    description: Allows to use PlayerLag feature
    default: op
  uglytroll.command.fakeban:
    description: Allows to use FakeBan feature
    default: op
  uglytroll.command.crash:
    description: Allows to use Crash feature
    default: op